;; guix environment --load=guix.scm
(use-modules (guix gexp)
             (guix packages)
             (guix build-system guile)
             (gnu packages guile)
             (gnu packages guile-xyz)
             (gnu packages game-development))
(package
 (name "griddy")
 (version "0.0.1")
 (source (local-file (dirname (current-filename))))
 (build-system guile-build-system)
 (synopsis "")
 (description "")
 (license "")
 (home-page "")
 (inputs `(("guile" ,guile-3.0)
           ("pfds" ,guile-pfds)
           ("picture-language" ,guile-picture-language)
           ;; needed for picture-language to work?
           ("readline" ,guile-readline)
           ("chickadee" ,guile-chickadee))))
