(define-module (griddy draw-chickadee)
  #:use-module (srfi srfi-1)
  #:use-module (oop goops)
  #:use-module (chickadee math vector)
  #:use-module (chickadee graphics path)
  #:use-module (chickadee graphics color)
  #:use-module (griddy core)
  #:export (draw-world))

(define (draw-actor actor)
  (define pos (vec2 (get-pos-x actor) (get-pos-y actor)))
  (draw-canvas (make-canvas (with-style ((fill-color green))
                              (fill (circle pos 10.0))))))

(define (draw-world world)
  (for-each draw-actor (get-actors world)))
